"""
run.py
------
Entry point. The case study explicitly requires a one-shot launch:

    python run.py

This boots the FastAPI server (which serves the HTML/CSS/JS frontend)
and triggers the Daily Campaign Briefing AS SOON AS the chat panel is
opened by the user — i.e. before any user typed input. The Briefing
itself is generated by the Supervisor orchestrating all 4 specialists.
"""
from __future__ import annotations

import os
import sys
import threading
import time
import webbrowser

import uvicorn
from dotenv import load_dotenv

load_dotenv()

PORT = int(os.getenv("GROWTHPULSE_PORT", "8000"))


def _open_browser_when_ready(url: str, delay: float = 1.5) -> None:
    def _open() -> None:
        time.sleep(delay)
        try:
            webbrowser.open(url)
        except Exception:  # pragma: no cover
            pass
    threading.Thread(target=_open, daemon=True).start()


def main() -> None:
    print("=" * 64)
    print(" GrowthPulse v1 — Cars24 Multi-Agent Performance Marketing")
    print("=" * 64)
    print(f"  Open  : http://127.0.0.1:{PORT}/")
    print(f"  Health: http://127.0.0.1:{PORT}/api/health")
    print()
    if not os.getenv("OPENAI_API_KEY") or "your" in os.getenv("OPENAI_API_KEY", "").lower():
        print("  [!] OPENAI_API_KEY not set — falling back to deterministic Mock LLM.")
        print("      Add OPENAI_API_KEY to .env for full natural-language answers.")
        print()

    _open_browser_when_ready(f"http://127.0.0.1:{PORT}/")
    uvicorn.run(
        "backend.app:app",
        host="127.0.0.1",
        port=PORT,
        reload=False,
        log_level="info",
    )


if __name__ == "__main__":
    sys.exit(main() or 0)
